### ISSUE TITLE
[suggestion] Add plasmovoice as an optional mod for easier communication in game

### ISSUE THREAD

**Issue by Khorne101** [SwitchCraftCC/issues#117]

**Comment by Lemmmy** [comment]
Thanks for the feature request. I think for now we'll leave this one out. Our primary means of voice chat right now is Discord, which is already enough of a hassle to moderate. Additionally, players have been using ComputerCraft's pocket computers/neural interfaces with speakers to achieve some level of in game voice chat, which is in line with the SwitchCraft spirit!

We're trying to avoid adding new mods as each mod is a significant new maintenance burden to take on. Not to say that our own code isn't a lot to deal with either, but at least we keep control over what we need and don't need, and can have it updated at our pace.
