### ISSUE TITLE
Feature request: programmatic access to chatbox commands

### ISSUE THREAD

**Issue by EmmaKnijn** [SwitchCraftCC/issues#159]
I'd like to have access to chatbox services from inside of CC.
This'd be a call like `chatbox.command("command name","arg1","arg2",...)` with the user and uuid matching the chatbox license owner's user and uuid.
I'd personally use this to monitor my own chatbox commands and notify me if they're down or misbehaving.

**Comment by Lemmmy** [comment]
Duplicate of #86
