### ISSUE TITLE
Discord verified roles for usernames

### ISSUE THREAD

**Issue by Lemmmy** [SwitchCraftCC/issues#22]
This feature request is part of me migrating my todo list to the issue tracker, one at a time :)

One of the small features on the larger roadmap is to add a verified role to the Discord bridge that automatically assigns your nickname (supporters can still have custom nicknames within reason, they will still be moderated). Sending messages to #server-chat will require the verified role - this will aid in nickname consistency and generally reduce spam risk.

**Comment by hugeblank** [comment]
To further expand on this idea: When a player mutes/ignores another player in game chat, that should also affect chats sent through the relay. What I mean is that if I muted you in-game, and you sent a chat through the discord relay it should not appear in my in-game chat.

**Comment by Lemmmy** [comment]
Oh that's a good idea too :D

**Comment by Lemmmy** [comment]
Feedback still wanted on the ignore change.

**Comment by hugeblank** [comment]
might be biased but my feedback is that it should happen

maybe I should break it out into a different issue report?
