### ISSUE TITLE
Creating posts in ComputerCraft-related forums about the server?

### ISSUE THREAD

**Issue by Kan18** [SwitchCraftCC/issues#25]
- https://forums.computercraft.cc/index.php?board=2.0 currently has no posts about SwitchCraft
- http://www.computercraft.info/forums2/index.php?/topic/26974-relaunched-1122-switchcraft-survival-krist-cctweaked180pr4-griefprevention/ is down (the image links no longer point anywhere) and the title is outdated

**Comment by Lemmmy** [comment]
I don't want to advertise the server right now
