### ISSUE TITLE
Inconsistency: join/leave message embeds on discord do not have "supporter halo", but death messages do

### ISSUE THREAD

**Issue by Kan18** [SwitchCraftCC/issues#41]
See the screenshot:
![image](https://user-images.githubusercontent.com/24967425/216221960-dabd6a16-7a4d-4f32-b437-3d386cb5bd18.png)
Since all of these messages (join, leave, death) put the player headshot in the same-ish location (right hand side of an embed) it could be expected that they have the same player headshot, but only the death message actually contains the supporter avatar effect, and the other two are normal

**Comment by Lemmmy** [comment]
Unfortunately this is not trivially fixable in the way I'd like at the moment as the join/leave messages are handled by the proxy which does not have access to supporter information - eventually this wil be moved to a supporter db microservice

Turning it off for death messages would be much easier though
