### ISSUE TITLE
Server restarts cause AFK message spam

### ISSUE THREAD

**Issue by Kan18** [SwitchCraftCC/issues#43]
<img width="435" alt="image" src="https://user-images.githubusercontent.com/24967425/216737366-67558251-5a22-473c-bf4e-d77d19a60c65.png">
After a server restart, everybody re-joins at once, so a couple minutes after the server starts, lots of AFK messages appear.

Suggestions:

- Combine the messages, so it could be something like "11 players have gone AFK"
- 
- Alternatively, carry over AFK status between server restarts. Maybe integrate it with the proxy/lobby somehow?

**Comment by Lemmmy** [comment]
![image](https://user-images.githubusercontent.com/858456/224078705-8df0977d-a385-43fe-b54b-d6d32f79ad2b.png)

I've batched them together - all AFKs in the same tick now show up in the same message, and same with all un-AFKs (they'll each show as their own message)
