### ISSUE TITLE
[SUGGESTION] Clumps mod

### ISSUE THREAD

**Issue by scmcgowen** [SwitchCraftCC/issues#51]
Add [Clumps mod](https://www.curseforge.com/minecraft/mc-mods/clumps)
This will make XP clump together and stop the problem of XP taking so long to collect on faster farms

**Comment by Lemmmy** [comment]
Note that we already have a lot of code modifying XP orb behavior so we it would be safer to replicate the required functionality ourselves than to add the Clumps mod.

Can you describe what you mean by "stop the problem of XP taking so long to collect on faster farms"?

**Comment by scmcgowen** [comment]
First: XP only gets collected one orb at a time, on a timer. That’s the problem 

quote from the wiki which still seems to hold true on SC3

`Unlike resources, experience points are picked up gradually: no matter how many orbs are in the range of the player, they are added to the player's experience one at a time (10 orbs/second). In extreme cases, this can result in the player being followed by a swarm of orbs for many seconds.`

This would be what I’d want fixed: either always combine XP orbs onto into one or make it collect all at once.
Clumps does both.

**Comment by Lemmmy** [comment]
Thanks for the explanation. For lag-reduction purposes we have the XP orb killers (which primarily serves the purpose of pruning runaway orbs). For everything else, it sounds like this is an intended vanilla mechanic to cap the output of XP farms. If your farm is automatic, just wait longer :)
