### ISSUE TITLE
feat: AFK in /list (discord)

### ISSUE THREAD

**Issue by piprett** [SwitchCraftCC/issues#58]
It would be useful to be able to see who is AFK when running `/list` on Discord.
Current look:
![image](https://user-images.githubusercontent.com/49862976/225637002-2b8405bc-d006-4db2-bf3a-ea8369ab0b3b.png)

**Comment by Lemmmy** [comment]
Not sure about this one.

**Comment by Lemmmy** [comment]
Not planning to implement this. I am quite happy with keeping AFK information exclusive to in-game/chatbox viewers. Additionally, the lists you see in /list and the pinned messages are handled by the proxy, which currently doesn't, and doesn't really need to, know about AFK players.
