### ISSUE TITLE
Chat ping sound isn't "Discord™" enough

### ISSUE THREAD

**Issue by Ale32bit** [SwitchCraftCC/issues#61]
### Describe the bug

A mention notification should invoke a feeling of having a social life with *real* friends, to do this, many sound designers (notably Discord™) research the effects of sound waves in the brain to stimulate the endorphin production.

Discord™ accomplished this with the classic Discord™ Ping™ (except when it's an @everyone Ping™).

### To reproduce

1. Yell in chat for someone to mention your name, in chat.
2. Open your ears and wait for the mention in chat.
3. Get disappointed by the sound.

### Expected behavior

A sense of pride and accomplishment should be felt upon hearing the classic Discord™ Ping™.

### Please confirm

- [ ] This is a serious issue and not a joke to annoy Lemmmy

**Comment by Lemmmy** [comment]
wot r u askin

**Comment by Ale32bit** [comment]
> wot r u askin

4 tis https://www.youtube.com/watch?v=VAMVKkBU90A
