### ISSUE TITLE
[Feature Request] Ability to run chatbox commands through chatboxes.

### ISSUE THREAD

**Issue by stealthy-coder** [SwitchCraftCC/issues#86]
I suggest a way to run `\` commands via chatboxes, authenticated with a chatbox key. The command syntax could be like `chatbox.run(command, arg1, arg2, arg3, arg4)` without any limit on arguments, or `chatbox.run(command, args)`, where args is a string formatted like `'arg arg2 arg3 arg4'`. When running this, the user would be identified as the chatbox license holder.

This could be useful for obtaining specific types of data from chatboxes that lack their own website API. Usage restrictions could be imposed, such as a queue size similar to chatbox.tell, or even smaller.

**Comment by Lemmmy** [comment]
Thanks for the suggestion - see here for my thoughts: https://discord.com/channels/198130613759246337/1057706496579883088/1097522531201716306
